[package]
name = "kroogate/maid"
description = "Object storage & cleaning utility"
version = "0.4.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/init.lua", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
